services:
  - type: web
    name: alemanaserigrafia
    env: static
    buildCommand: pnpm install && pnpm run build
    staticPublishPath: ./dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html