services:
  - type: web
    name: alemanaserigrafia
    env: static
    buildCommand: npm install -g pnpm && pnpm install && pnpm run build:linux
    staticPublishPath: ./dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html